import { ThemeConfig } from '../types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'emerald-night',
    name: 'Emerald Night (زمرد لیل)',
    mode: 'dark',
    bg: '#0a140e',
    surface: '#122218',
    surfaceSecondary: '#1a2e22',
    border: '#243e2f',
    primary: '#249052',
    primaryHover: '#2db867',
    accent: '#d4af37',
    text: '#f0f6f2',
    textMuted: '#94aba0',
    cardBg: '#13241a'
  },
  {
    id: 'lapis-dawn',
    name: 'Lapis Dawn (لازورد فجر)',
    mode: 'dark',
    bg: '#0a0f1d',
    surface: '#11182c',
    surfaceSecondary: '#19233f',
    border: '#24335a',
    primary: '#2e5ec4',
    primaryHover: '#3b71e8',
    accent: '#e6a13d',
    text: '#f0f4fc',
    textMuted: '#96a6c9',
    cardBg: '#131c34'
  },
  {
    id: 'amethyst-dusk',
    name: 'Amethyst Dusk (جمشت غسق)',
    mode: 'dark',
    bg: '#110a1c',
    surface: '#1c122c',
    surfaceSecondary: '#271b3d',
    border: '#3c295c',
    primary: '#7747c4',
    primaryHover: '#8b59e0',
    accent: '#d9a941',
    text: '#f5effc',
    textMuted: '#a797be',
    cardBg: '#1e1430'
  },
  {
    id: 'pearl-light',
    name: 'Pearl Light (درر بيضاء)',
    mode: 'light',
    bg: '#f8f6f0',
    surface: '#ffffff',
    surfaceSecondary: '#f2eee3',
    border: '#e0dacf',
    primary: '#1d6f3e',
    primaryHover: '#165731',
    accent: '#b88928',
    text: '#1b2620',
    textMuted: '#5d6f65',
    cardBg: '#ffffff'
  },
  {
    id: 'desert-sand',
    name: 'Desert Sand (رمال الصحراء)',
    mode: 'light',
    bg: '#faf6ee',
    surface: '#ffffff',
    surfaceSecondary: '#f4ede0',
    border: '#e4d8c5',
    primary: '#9c6f1a',
    primaryHover: '#7e5812',
    accent: '#c96a29',
    text: '#2b2318',
    textMuted: '#6e6252',
    cardBg: '#ffffff'
  },
  {
    id: 'sky-light',
    name: 'Sky Blue (أزرق سماوي)',
    mode: 'light',
    bg: '#f1f7fc',
    surface: '#ffffff',
    surfaceSecondary: '#e6f0fa',
    border: '#d0e1f0',
    primary: '#176bb8',
    primaryHover: '#125492',
    accent: '#359fce',
    text: '#17222c',
    textMuted: '#586b7c',
    cardBg: '#ffffff'
  }
];
